### ISSUE TITLE
Visual code is unable to run in debugger mode when using this library

### ISSUE THREAD

**Issue by john-yick** [naptha/tesseract.js#102]
First off great library for OCR'ing works perfectly fine when running calling the app by 'node server.js' The issue arises when pressing F5 with the tesseract.js library it seems to crash the debugger within visual code.

Debugger listening on port 48412
[2017-02-07 21:42:01.693] [INFO] log - [port:2000] - started
Error: listen EADDRINUSE :::48412
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Agent.Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Agent.Server.listen (net.js:1385:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:86:44)
    at node.js:449:3

Any help around this would be great, only tesseract.js seems to cause this issue for us.

**Comment by aspirisen** [comment]
Any updates? It really stops using this library
Thanks.

**Comment by jeromewu** [comment]
In fact, I think you should open this issue in vscode repository as I never use vscode and totally don't know how to fix (or reproduce) this issue, close for now.
