### ISSUE TITLE
Azure Functions and Tesseract

### ISSUE THREAD

**Issue by JustSmitty** [naptha/tesseract.js#114]
I am working to get Tesseract to work with Azure Functions.  I have gotten the library loaded, and the function is setup to be triggered with an image is loaded up to Blob storage.

My issue is when I try to run the function, I am getting the error:
2017-03-04T03:14:30.594 Error: **Path must be a string without null bytes**
    at nullCheck (fs.js:135:14)
    at Object.fs.readFile (fs.js:287:8)
    at loadImage (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\node\index.js:46:12)
    at Object.sendPacket (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\node\index.js:26:5)
    at TesseractJob._send (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\common\job.js:43:17)
    at _delay.job (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\index.js:32:8)
    at Array._queue.push.e (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\index.js:54:4)
    at TesseractWorker._dequeue (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\index.js:63:18)
    at TesseractWorker._delay (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\index.js:56:30)
    at TesseractWorker.recognize (D:\home\site\wwwroot\PullText\node_modules\tesseract.js\src\index.js:24:15).

The function is very simple right now in what it is trying to do.  Here is the code in the function:

`var tesseract = require('tesseract.js');

module.exports = function (context, myBlob) {
        
    tesseract.recognize(myBlob)
    .then(function(result){
      context.log("Log1: ",result);
      context.log("Log1: ",result.text);
    })
    .catch(function(err) {
        context.log("Error: ",err);
    });
    
    context.done();
};`

**Comment by ryankelley** [comment]
@JustSmitty Any luck getting this to work?

**Comment by jeromewu** [comment]
Please try the latest version (2.0.0-beta.1) to see if the issue exists, close for now.
