### ISSUE TITLE
How to load image from <img>?

### ISSUE THREAD

**Issue by nemanjapetrovic** [naptha/tesseract.js#115]
I am trying to OCR image from `<img>` tag but I am getting some exceptions, am I wrong somewhere?

What is the right way to OCR image from `<img>` tag.

Exceptions:

> Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at loadImage (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:412:26)
    at loadImage (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:409:16)
    at Object.sendPacket (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:354:5)
    at TesseractJob._send (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:549:21)
    at https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:643:9
    at Array.<anonymous> (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:673:5)
    at TesseractWorker._dequeue (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:683:19)
    at TesseractWorker._delay (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:675:32)
    at TesseractWorker.recognize (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js:635:16)
    at runOCR (file:///C:/Users/Nemanja/Desktop/tesseract-test/index.html:25:14)

> Access to Image at 'file:///C:/Users/Nemanja/Desktop/tesseract-test/test.jpg' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.

```<html>
<head>

</head>
<body>	
	<input type="button" id="go_button" value="Run" />
	<img src="test.jpg" id="ocr" />	
    
	<script src="jquery.js"></script>
	<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>

	<script>
	$(document).ready(function(){
	
		
		$("#go_button")	.click( function() {				
				runOCR();
		});
		
		var runOCR = function() {
			var img = new Image();			
			img.src = document.getElementById('ocr').src;
	
			Tesseract.recognize(img)
				.progress(function  (p) { console.log('progress', p)    })
				.then(function (result) { console.log('result', result) })
		}
		
	});
	</script>
	
</body>
</html>`

**Comment by tetreault** [comment]
Your problem is one of CORS. In your own error message: 

> "Access to Image at 'file:///C:/Users/Nemanja/Desktop/tesseract-test/test.jpg' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access."

**Comment by atiladelcanton** [comment]
Can solve, I have the same problem
