### ISSUE TITLE
Errors often don't actually hit the catch handler

### ISSUE THREAD

**Issue by osdiab** [naptha/tesseract.js#122]
Node.js 6.4.0, tesseract.js 1.0.10

I tried to provide an image path that didn't exist; instead of `catch` being called with that error, it just printed the `ENOENT` to my console and continued running the program. Same went for putting a non-image as input.

It would be a lot more elegant if all errors, including ones like this, ended up in the `catch` handler.

**Comment by shredd** [comment]
I am having the same problem. tesseract.js accepts animated GIF files however is unable to process them. The error handler is not invoked and the tesseract instance is left unable to process any other images either, though the Node application does not crash.

**Comment by motin** [comment]
This may be fixable by compiling with NODEJS_CATCH_EXIT=0, or at least that was the solution for these libraries: https://github.com/uber/h3-js/issues/7, https://github.com/ethereum/solc-js/issues/174

**Comment by marcelcremer** [comment]
Hey @motin ,

both referenced issues are solved, but the tesseract problem seems not to be. I encounter an IPC_CHANNEL_CLOSED error which also is not triggering the Promise catch method (and kills my whole server instance btw...):

Node v10.13.0
"tesseract.js": "^1.0.19",

Error stack:
```
[REST]     →  Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
[REST]     →      at ChildProcess.target.send (internal/child_process.js:628:16)
[REST]     →      at img (...\server\server\node_modules\.registry.npmjs.org\tesseract.js\1.0.19\node_modules\tesseract.js\src\node\index.js:26:25)
[REST]     →      at loadImage (...\server\server\node_modules\.registry.npmjs.org\tesseract.js\1.0.19\node_modules\tesseract.js\src\node\index.js:88:5)
[REST]     →      at loadImage (...\server\server\node_modules\.registry.npmjs.org\tesseract.js\1.0.19\node_modules\tesseract.js\src\node\index.js:86:16)
[REST]     →      at ...\server\server\node_modules\.registry.npmjs.org\tesseract.js\1.0.19\node_modules\tesseract.js\src\node\index.js:71:17
[REST]     →      at ...\server\node_modules\.registry.npmjs.org\png.js\0.2.1\node_modules\png.js\PNGReader.js:409:4
[REST]     →      at Inflate.cb (...\server\node_modules\.registry.npmjs.org\png.js\0.2.1\node_modules\png.js\PNGReader.js:201:3)
[REST]     →      at Inflate.zlibBufferOnEnd (zlib.js:123:10)
[REST]     →      at Inflate.emit (events.js:187:15)
[REST]     →      at endReadableNT (_stream_readable.js:1094:12)
[REST]     →      at process._tickCallback (internal/process/next_tick.js:63:19)
```

Calling code (in async function):
```
...
try{
    return (await Tesseract.recognize(filename)).text;
}
catch(e)
{
    this.logger.error('Image could not be processed: ', e);
}
...
```

Catch is not triggered and the process exited...

**Comment by jeromewu** [comment]
It works above 2.0.0-beta.1, feel free to try and reopen if the issue exists.

**Comment by rvndorado** [comment]
I have encountered the same issue with tesseract.js version 2.1.1, express 4.17.1, and node 12.6.1.

It seems that the catch of the promise is not triggering.

Here is my code block:

```
const Tesseract = require('tesseract.js');
exports.postImage = (req, res, next) => {
    
    const image = req.body.image;
    const language = req.body.language;
    let hasError = false;
    let errorMessage = '';
    let outputText = '';

    Tesseract.recognize(image, language, { })
      .then(({ data: { text } }) => {
        outputText = text;
        res.status(200).json({
          hasError: hasError,
          errorMessage: errorMessage,
          outputText: outputText,
        });
      })
      .catch((error) => {
        hasError = true;
        errorMessage = "Error Message;
        res.status(400).json({
          hasError: hasError,
          errorMessage: errorMessage,
          outputText: outputText,
        });
      });


};
```

Error message encountered

```
Error in pixReadMem: Unknown format: no pix returned
Error in pixGetSpp: pix not defined
Error in pixGetDimensions: pix not defined
Error in pixGetColormap: pix not defined
Error in pixCopy: pixs not defined
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixGetYRes: pix not defined
Error in pixClone: pixs not defined
Please call SetImage before attempting recognition.
```
