### ISSUE TITLE
Nodejs & tesseract.js@1.0.10 Ugly Crash

### ISSUE THREAD

**Issue by nyquist212** [naptha/tesseract.js#124]
I installed via npm and attempted to run the sample code in the README,

```
  Tesseract.recognize('public/images/72 drawing A.jpg')
         .progress(function  (p) { console.log('progress', p)    })
         .then(function (result) { console.log('result', result) })
```
Unfortunately, I don't get much from this error message and hope someone can tell me if it's something I can fix? Admittedly, it's a pretty ambitious image (~2MB) I've thrown at it...

```
[nodemon] starting `node bin/www`

<--- Last few GCs --->

[19278:0x102804600]    38456 ms: Mark-sweep 657.2 (694.9) -> 651.9 (694.9) MB, 187.7 / 0.0 ms  allocation failure GC in old space requested
[19278:0x102804600]    38639 ms: Mark-sweep 651.9 (694.9) -> 651.8 (694.9) MB, 183.4 / 0.0 ms  allocation failure GC in old space requested
[19278:0x102804600]    38838 ms: Mark-sweep 651.8 (694.9) -> 651.8 (658.9) MB, 198.3 / 0.0 ms  last resort gc 
[19278:0x102804600]    39027 ms: Mark-sweep 651.8 (658.9) -> 651.8 (658.9) MB, 189.5 / 0.0 ms  last resort gc 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1170762c0d39 <JS Object>
    1: from [native array.js:~1065] [pc=0x137ffa672b0e](this=0x1170762a0919 <JS Function Array (SharedFunctionInfo 0x11707626b899)>,bx=0x96adb892d1 <an Uint8Array with map 0x28617ec1afc1>,by=0x117076204311 <undefined>,bl=0x117076204311 <undefined>)
    2: arguments adaptor frame: 1->3
    3: loadImage [/Users/Admin/Public/rlxocrtest/node_modules/tesseract.js/src/node/index.js:93] [pc=0x137ffa66...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedSmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)0> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedSmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)0> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedSmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)0> >::Add(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/usr/local/bin/node]
 8: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [/usr/local/bin/node]
 9: v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::JSObject::AccessorInfoHandling) [/usr/local/bin/node]
10: v8::internal::JSObject::CreateDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::ShouldThrow) [/usr/local/bin/node]
11: v8::internal::Runtime_CreateDataProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x137ffa2063a7
[nodemon] app crashed - waiting for file changes before starting...
```
 running node (version 7.9.0) with
```
node --max-old-space-size= 8192 ocr.js
```
Didn't help...
```
internal/child_process.js:648
    var string = JSON.stringify(message) + '\n';
                      ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at ChildProcess.target._send (internal/child_process.js:648:23)
    at ChildProcess.target.send (internal/child_process.js:560:19)
    at /Users/Admin/Public/rlxocrtest/node_modules/tesseract.js/src/node/index.js:28:25
    at loadImage (/Users/Admin/Public/rlxocrtest/node_modules/tesseract.js/src/node/index.js:96:5)
    at loadImage (/Users/Admin/Public/rlxocrtest/node_modules/tesseract.js/src/node/index.js:94:16)
    at loadImage (/Users/Admin/Public/rlxocrtest/node_modules/tesseract.js/src/node/index.js:83:13)
    at /Users/Admin/Public/rlxocrtest/node_modules/tesseract.js/src/node/index.js:48:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Comment by nyquist212** [comment]
Looks like this is an image file too big problem ...

**Comment by bcalik** [comment]
Is there any other solution?

**Comment by b4dnewz** [comment]
it is really inconvenient not to be able to use it with large images.. even tho I read in a SO answer that a guy is using it with 10mb or larger images.. but for me isn't working I got the same js heap error.

**Comment by jeromewu** [comment]
I think the only solution is to resize the image or crop the image, there is not too much we can help when it comes to extreme cases.
