### ISSUE TITLE
Problem installing on ubuntu 16.10

### ISSUE THREAD

**Issue by ashwanikumar04** [naptha/tesseract.js#128]
Hello:
I am trying to install on Ubuntu using 
```
npm install tesseract --save
```
But I get the following error, 
```
                                            ^~~~~~~~~
../src/tesseract_baseapi.h:34:52: error: ‘Arguments’ does not name a type
     static Handle<Value> WhitelistCharacters(const Arguments& args);
                                                    ^~~~~~~~~
../src/tesseract_baseapi.h:35:47: error: ‘Arguments’ does not name a type
     static Handle<Value> SetPageSegMode(const Arguments& args);
                                               ^~~~~~~~~
../src/tesseract_baseapi.h:36:38: error: ‘Arguments’ does not name a type
     static Handle<Value> Clear(const Arguments& args);
                                      ^~~~~~~~~
../src/tesseract_baseapi.h:37:36: error: ‘Arguments’ does not name a type
     static Handle<Value> End(const Arguments& args);
                                    ^~~~~~~~~
In file included from ../src/tesseract_bindings.cc:10:0:
../src/leptonica_pix.h:21:41: error: expected class-name before ‘{’ token
 class PixWrap : public node::ObjectWrap {
                                         ^
../src/leptonica_pix.h:31:31: error: ‘Arguments’ does not name a type
     static PIX* PixRead(const Arguments& args);
                               ^~~~~~~~~
../src/leptonica_pix.h:32:36: error: ‘Arguments’ does not name a type
     static Handle<Value> New(const Arguments& args);
                                    ^~~~~~~~~
../src/leptonica_pix.h:33:40: error: ‘Arguments’ does not name a type
     static Handle<Value> GetPath(const Arguments& args);
                                        ^~~~~~~~~
../src/leptonica_pix.h:34:39: error: ‘Arguments’ does not name a type
     static Handle<Value> Reload(const Arguments& args);
                                       ^~~~~~~~~
tesseract_bindings.target.mk:106: recipe for target 'Release/obj.target/tesseract_bindings/src/tesseract_bindings.o' failed
make: *** [Release/obj.target/tesseract_bindings/src/tesseract_bindings.o] Error 1
make: Leaving directory '/mnt/Development/Projects/test/node_modules/tesseract/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

```

I am not sure what am I missing here?

**Comment by kotAPI** [comment]
It could probably be an unstable nodejs version or so, could you reinstall stable versions of nodejs and npm and try installing tesseract it again?

**Comment by IlyaRadinsky** [comment]
Same error on macOS, nodejs v8.8.1

**Comment by kotAPI** [comment]
This needs a fix.

**Comment by IlyaRadinsky** [comment]
I found out the problem - it's in the documentation. The misunderstanding arose because of the following:
```
> yarn add tesseract
> npm install tesseract.js --save
```
But to install this npm we should use `tesseract.js`
I prepared a super PR https://github.com/naptha/tesseract.js/pull/163 :)

**Comment by amin0no** [comment]
@IlyaRadinsky Thanks you, are a life saver.
