### ISSUE TITLE
Tesseract.js + Node pkg for exe distribution fails with missing require.

### ISSUE THREAD

**Issue by johanvdb** [naptha/tesseract.js#138]
When making use of https://www.npmjs.com/package/pkg to produce a redistributable binary of a node.js project, the following error occurs when trying to use Tesseract. 

See https://gitlab.com/johantheitguy/tesseractjs-pkg for an example project (see scripts in package.json).

```
Error: Cannot find module '../common/worker.js'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1217:46)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1101:31)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snapshot/tesseract-pkg/node_modules/tesseract.js/src/node/worker.js:1:83)
    at Module._compile (module.js:570:32)
    at Module._compile (pkg/prelude/bootstrap.js:1198:32)
    at Object.Module._extensions..js (module.js:579:10)
```

I realize this might be a pkg issue, but I have revisited their documentation a hundred times and I cannot see why it would not work. I was hoping someone with more experience of how the worker is being loaded might understand how to resolve this.

Running the same app without pkg works as expected. The OCR result is "hello".

Thanks in advance!

**Comment by johanvdb** [comment]
This was just resolved by the developer of pkg - https://github.com/zeit/pkg/issues/183
