### ISSUE TITLE
connect ETIMEDOUT 78.16.49.15:80

### ISSUE THREAD

**Issue by axetroy** [naptha/tesseract.js#154]
Invalid network?

```bash
$ node index.js

pre-main prep time: 41 ms
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 78.16.49.15:80
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```

And I canot ping through the server 78.16.49.15

**Comment by messi1991** [comment]
Hello i have encountered this problem, how do you solve it?

**Comment by axetroy** [comment]
@messi1991 
换一个模块, node-tesseract就可以

**Comment by messi1991** [comment]
@axetroy 我去，亲切的汉语，谢谢

**Comment by zhouzhili** [comment]
谢谢
