### ISSUE TITLE
Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

### ISSUE THREAD

**Issue by MickyDNet** [naptha/tesseract.js#173]
Trying to convert any text gives me this, I have currently tried converting english.

`progress { status: 'loading tesseract core' }
progress { status: 'loaded tesseract core' }
progress { status: 'initializing tesseract', progress: 0 }
pre-main prep time: 36 ms
progress { status: 'initializing tesseract', progress: 1 }
progress { status: 'loading eng.traineddata', progress: 0 }
progress { status: 'loading eng.traineddata', progress: 1 }
progress { status: 'initializing api', progress: 0 }
Failed loading language 'eng'
Tesseract couldn't load any languages!
progress { status: 'initializing api', progress: 0.3 }
progress { status: 'initializing api', progress: 0.6 }
progress { status: 'initializing api', progress: 1 }
progress { status: 'recognizing text', progress: 0 }
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:32:26)
    at Object.ka [as abort] (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:507:108)
    at _abort (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:373:173)
    at $L (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:383:55709)
    at jpa (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:388:22274)
    at lT (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:387:80568)
    at mT (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:387:80700)
    at Array.BS (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:387:69011)
    at bP (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:383:110121)
    at jT (H:\My Documents\NodeJS\OCRDiscordJS\node_modules\tesseract.js-core\index.js:387:80280)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.`

**Comment by pbaio** [comment]
I too am having this issue while attempting to demo this project using the Simple Example given in the README. 

#### Environment Info
- OS: OS X 10.13.2
- NodeJS Version: v9.1.0

#### Here is my code:
```javascript
const Tesseract = require('tesseract.js')
const path = require('path')

const imageToOcr = path.join(__dirname, 'image-to-ocr.png')

Tesseract.recognize(imageToOcr)
  .progress(p => console.log('progress', p))
  .then(result => console.lg(result))
  .catch(err => console.log(err))
```
#### Console Output & Error
> progress { status: 'loading tesseract core' }
progress { status: 'loaded tesseract core' }
progress { status: 'initializing tesseract', progress: 0 }
pre-main prep time: 31 ms
progress { status: 'initializing tesseract', progress: 1 }
progress { status: 'loading eng.traineddata', progress: 0 }
progress { status: 'loading eng.traineddata', progress: 1 }
progress { status: 'initializing api', progress: 0 }
Failed loading language 'eng'
Tesseract couldn't load any languages!
progress { status: 'initializing api', progress: 0.3 }
progress { status: 'initializing api', progress: 0.6 }
progress { status: 'initializing api', progress: 1 }
progress { status: 'recognizing text', progress: 0 }
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

>/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
>abort() at Error
    at Na (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:32:26)
    at Object.ka [as abort] (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:507:108)
    at _abort (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:373:173)
    at $L (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:383:55709)
    at jpa (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:388:22274)
    at lT (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:387:80568)
    at mT (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:387:80700)
    at BS (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:387:69011)
    at bP (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:383:110121)
    at jT (/Workspaces/tesseract-ocr-sample/node_modules/tesseract.js-core/index.js:387:80280)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by pbaio** [comment]
After looking around the issues here further, downloading the `eng.traineddata.gz` from the [language data](https://github.com/naptha/tessdata/tree/gh-pages/3.02) did the trick.

It seems the mechanism that is responsible for downloading the `eng.traineddata.gz` is broken. When initially running `Tesseract.recognize()` I noticed that the `eng.traineddata` is created locally within my project directory but it is empty. It wasn't until I overwrote that file with the contents of the gzip file that Tesseract was able to OCR my image.

**Comment by micheleriva** [comment]
Hi @pbaio ,
I followed your example but i still get this error.
I am calling `eng.traineddata` script as follow:

```js
const TESSERACT = Tesseract.create({
  workerPath: `${window.location.origin}/js/ocr_worker.js`,
  langPath:   `${window.location.origin}/traineddata/eng.traineddata`
})
````
any idea?
