### ISSUE TITLE
Tesseract couldn't load any languages!

### ISSUE THREAD

**Issue by dylan-wu** [naptha/tesseract.js#190]
Calling detect result in error. 
```js
  var Tesseract = require('tesseract.js')
  Tesseract.detect(path)
    .then(function(result){
        console.log(result)
    })
```

Here is the error:
```bash
$ node index.js
pre-main prep time: 51 ms
Failed loading language 'osd'
Tesseract couldn't load any languages!
Number of blobs post-filtering = 238
Number of blobs to try = 238
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:32:26)
    at Object.ka [as abort] (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:507:108)
    at _abort (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:373:173)
    at $L (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:383:55709)
    at jpa (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:388:22274)
    at DC (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:391:62311)
    at CC (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:391:61582)
    at BC (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:391:60969)
    at AC (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:391:60368)
    at Jj (/Users/admin/projects/read-pdf/node_modules/tesseract.js-core/index.js:382:34615)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by webber0928** [comment]
https://github.com/naptha/tesseract.js/issues/136

#136

**Comment by jeromewu** [comment]
Should be CDN issue at the moment, fixed now.

**Comment by dylan-wu** [comment]
Thank you, now I can breath, I've been holding my breath.

**Comment by jeromewu** [comment]
Glad that you can finally breath :smiley:
