### ISSUE TITLE
TypeError: string.match is not a function

### ISSUE THREAD

**Issue by jinhwanee93** [naptha/tesseract.js#195]
As soon as I run the ocr.js file I get this error:

``` node ocr.js```

```/Users/alexandrekim/wndrfl/OCR-Tesseract-API/node_modules/is-url/index.js:27
  var match = string.match(protocolAndDomainRE);
                     ^

TypeError: string.match is not a function
    at isUrl (/Users/alexandrekim/wndrfl/OCR-Tesseract-API/node_modules/is-url/index.js:27:22)
    at loadImage (/Users/alexandrekim/wndrfl/OCR-Tesseract-API/node_modules/tesseract.js/src/node/index.js:35:8)
    at /Users/alexandrekim/wndrfl/OCR-Tesseract-API/node_modules/tesseract.js/src/node/index.js:48:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```

This error did not occur during my initial test with the library, until I changed the eng.traineddata file...

I tried re-applying my old eng.traineddata file, but no luck.

Any help would be appreciated.

**Comment by yonmey** [comment]
@jinhwanee93 I created a PR to fix this problem: https://github.com/naptha/tesseract.js/pull/196

**Comment by jinhwanee93** [comment]
@yonmey Thanks!
