### ISSUE TITLE
Using Tesseratct in Node.js 

### ISSUE THREAD

**Issue by mikeyfev1** [naptha/tesseract.js#228]
I have read most of the other solutions to this problem of tesseract.js giving the error message: **Tesseract couldn't load any languages!**. I am getting the same problem and have tried many of the given solutions, but I still cannot get this to work. Here is my scenario:

OS: **Windows 10, 64-bit**
Node version: **8.11.3**
Project folder: **c:\projects\tesse**

Script:
```
import Tesseract from 'tesseract.js'

Tesseract.create({
  langPath: "c:/projects/tesse/langs"
}).recognize("c:/projects/tesse/image.jpg", "eng")
    .progress(p => console.log("PROGRESS", p))
    .then(result => console.log("THEN\n", result))
    .catch(err => console.error("CATCH\n", err))
    .finally(e => {
      console.log("FINALLY\n", e)
      process.exit()
  })
```
(I am using babel to support the ES6 style under node.js).

In my project folder I created a subfolder named **langs** and I downloaded/extracted the file **eng.traineddata.gz** into that subfolder from the git repository. So I have one file in the folder **c:\projects\tesse\langs** which is named **eng.traineddata**.

Output:
```
PROGRESS { status: 'loading tesseract core' }
PROGRESS { status: 'loaded tesseract core' }
PROGRESS { status: 'initializing tesseract', progress: 0 }
pre-main prep time: 65 ms
PROGRESS { status: 'initializing tesseract', progress: 1 }
PROGRESS { status: 'loading eng.traineddata', progress: 0 }
PROGRESS { status: 'loading eng.traineddata', progress: 1 }
PROGRESS { status: 'initializing api', progress: 0 }
Failed loading language 'eng'
Tesseract couldn't load any languages!
PROGRESS { status: 'initializing api', progress: 0.3 }
PROGRESS { status: 'initializing api', progress: 0.6 }
PROGRESS { status: 'initializing api', progress: 1 }
PROGRESS { status: 'recognizing text', progress: 0 }
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

c:\projects\tesse\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (c:\projects\tesse\node_modules\tesseract.js-core\index.js:32:26)
    at Object.ka [as abort] (c:\projects\tesse\node_modules\tesseract.js-core\index.js:507:108)
    at _abort (c:\projects\tesse\node_modules\tesseract.js-core\index.js:373:173)
    at $L (c:\projects\tesse\node_modules\tesseract.js-core\index.js:383:55709)
    at jpa (c:\projects\tesse\node_modules\tesseract.js-core\index.js:388:22274)
    at lT (c:\projects\tesse\node_modules\tesseract.js-core\index.js:387:80568)
    at mT (c:\projects\tesse\node_modules\tesseract.js-core\index.js:387:80700)
    at BS (c:\projects\tesse\node_modules\tesseract.js-core\index.js:387:69011)
    at bP (c:\projects\tesse\node_modules\tesseract.js-core\index.js:383:110121)
    at jT (c:\projects\tesse\node_modules\tesseract.js-core\index.js:387:80280)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```
Does anyone know how to get this to work?

**Comment by klunejko** [comment]
Having the same exact issue with Windows 7 x64, Node v7.7.2

**Comment by thapliyalmanoj** [comment]
Same Issue here  Windows X 64,  node 8.11.1.

**Comment by AJLoveChina** [comment]
Same Issue on Windows 10, node 8.x
I wonder if this library really works? ! @bijection 
Or the docs/guide is really terrible?

**Comment by OscarGodson** [comment]
Same issue. Is this repo deprecated? I have the simplest example and it gives me that. On Mac OS

**Comment by aamjsadiq** [comment]
I had the same issue, I tried by downloading the raw files using curl (or wget) and it solved my issue :)

**Comment by jeromewu** [comment]
In the latest version (v1.0.14+), we have updated the link to download the tessdata and so on, please try and see whether the issue remains the same.
