### ISSUE TITLE
getting error while parsing image

### ISSUE THREAD

**Issue by PrasannaBrabourame** [naptha/tesseract.js#242]
`var job1 = Tesseract.recognize('./img1.png');`

getting error normal image parsing

**Comment by jeromewu** [comment]
@PrasannaBrabourame 

Can you kindly help to provide the error message? Thanks.

**Comment by PrasannaBrabourame** [comment]
@jeromewu 

Please find the below error details.

`Failed loading language 'eng'
Tesseract couldn't load any languages!
{ status: 'initializing api', progress: 0.3 }
{ status: 'initializing api', progress: 0.6 }
{ status: 'initializing api', progress: 1 }
{ status: 'recognizing text', progress: 0 }
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:32:26)
    at Object.ka [as abort] (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:507:108)
    at _abort (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:373:173)
    at $L (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:383:55709)
    at jpa (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:388:22274)
    at lT (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:387:80568)
    at mT (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:387:80700)
    at BS (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:387:69011)
    at bP (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:383:110121)
    at jT (D:\PRASANNA\Files\PROJECTS\GitHub\Image2Text\node_modules\tesseract.js-core\index.js:387:80280)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.`

**Comment by jeromewu** [comment]
Looks like tesseract.js fail to download *.traineddata, it may cause by network issue or the sunsetting of CDN.

Please try to update to v1.0.12 / latest version of tesseract.js to see if the problem persist.

**Comment by PrasannaBrabourame** [comment]
after installing tesseract.js v1.0.12 still the same error occurs.

**Comment by jeromewu** [comment]
I think there might be some network issue in your environment.

Please try to access the link below to check whether you can access the website we store the *.traineddata.gz

https://cdn.jsdelivr.net/gh/naptha/tessdata@gh-pages/3.02/eng.traineddata.gz

If you are unable to download from the link above, anther approach is to use offline approach

- Download desired lang data from [tessdata](https://github.com/naptha/tessdata/tree/gh-pages/3.02) repository
- gunzip traineddata with following command

```
$ gzip -d eng.traineddata.gz
```
- put *.traineddata next to your *.js file

Hope it helps.

**Comment by jeromewu** [comment]
Close as no further replies.

**Comment by SubashMo-Kore** [comment]
![image](https://github.com/naptha/tesseract.js/assets/94962364/4e7d7937-0166-44f9-9132-afe7aacd7e75)
Getting the same issue
