### ISSUE TITLE
Failed loading language 'chi_tra'

### ISSUE THREAD

**Issue by fouber** [naptha/tesseract.js#250]
![1-0](https://user-images.githubusercontent.com/536297/48822108-b574ad00-ed96-11e8-9ec0-974365666374.png)

```
pre-main prep time: 31 ms
Failed loading language 'chi_tra'
Tesseract couldn't load any languages!
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:32:26)
    at Object.ka [as abort] (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:507:108)
    at _abort (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:373:173)
    at $L (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:383:55709)
    at jpa (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:388:22274)
    at lT (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:387:80568)
    at mT (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:387:80700)
    at BS (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:387:69011)
    at bP (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:383:110121)
    at jT (/Users/fouber/temp/ocr/node_modules/tesseract.js-core/index.js:387:80280)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by fouber** [comment]
![image](https://user-images.githubusercontent.com/536297/48822179-02588380-ed97-11e8-9a46-a4194f15ca7b.png)

The downloaded traineddata ``chi_tra.traineddata`` file size is 0

**Comment by jeromewu** [comment]
This issue is caused by unstable network connection, please remove the chi_tra.traineddata and run the script again.

If you still have the 0 byte chi_tra.traineddata, you can download it from [HERE]( https://github.com/naptha/tessdata/tree/gh-pages/3.02) and unzip with

```
$ gzip -d chi_tra.traineddata
```

Related issues: #242

**Comment by fouber** [comment]
@jeromewu 

https://cdn.jsdelivr.net/gh/naptha/tessdata@gh-pages/3.02/chi_tra.traineddata.gz

The download link above responsed:

> File size exceeded the configured limit of 20 MB.

It's the limit of jsDelivr, not caused by unstable network connection, I fixed this by download the file manually at the link below:

> https://github.com/naptha/tessdata/raw/gh-pages/3.02/chi_tra.traineddata.gz

**Comment by jeromewu** [comment]
Fix by v1.0.14, now we use github page for hosting tessdata
