### ISSUE TITLE
png parsing failed.

### ISSUE THREAD

**Issue by semonw** [naptha/tesseract.js#252]
when trying to recognize a png, as follows,
https://login.sina.com.cn/cgi/pin.php?r=47228573&s=0&p=tc-fe8898878e5cc217485704b471ef878c845c

**then, this happened:  it seems the underlying library png.js is not running correctly..**

Error: unkown filtered scanline
    at PNGReader.interlaceNone (E:\node_modules\png.js\PNGReader.js:231:19)
    at E:\node_modules\png.js\PNGReader.js:193:12
    at Inflate.onEnd (zlib.js:131:5)
    at emitNone (events.js:111:20)
    at Inflate.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jeromewu** [comment]
@semonw 

This should be fixed in the next version of tesseract.js, please install it by:

```
$ npm install tesseract.js@next
```
