### ISSUE TITLE
NodeJS Tesseract 1.0.14 

### ISSUE THREAD

**Issue by nzraad** [naptha/tesseract.js#258]
**My Code**
```javascript
const Tesseract = require("tesseract.js");
const express = require("express");
const fileUpload = require("express-fileupload");

const app = express();
const port = 3000;
app.use(express.json());
app.use(fileUpload());

app.post("/pdfParse", function(req, res) {
	Tesseract.recognize(req.files.foo).progress(function(message) {
		console.log("progress is: ", message);
	});
});

app.listen(port, () =>
	console.log(`Port 3000`)
);
```
**Error Code**
```
progress is:  { status: 'loading tesseract core' }
progress is:  { status: 'loaded tesseract core' }
progress is:  { status: 'initializing tesseract', progress: 0 }
pre-main prep time: 50 ms
progress is:  { status: 'initializing tesseract', progress: 1 }
progress is:  { status: 'loading eng.traineddata', progress: 0 }
progress is:  { status: 'loading eng.traineddata', progress: 1 }
progress is:  { status: 'initializing api', progress: 0 }
progress is:  { status: 'initializing api', progress: 0.3 }
progress is:  { status: 'initializing api', progress: 0.6 }
Error in pixRemoveColormap: pixs must be {1,2,4,8} bpp
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixCreateHeader: depth must be {1, 2, 4, 8, 16, 24, 32}
Error in pixCreateNoInit: pixd not made
Error in pixCreateTemplateNoInit: pixd not made
Error in pixCreateTemplate: pixd not made
Error in pixCopy: pixd not made
progress is:  { status: 'initializing api', progress: 1 }
3
3

/Users/naseemraad/Developer/***/node_modules/tesseract.js-core/index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort(3) at Error
    at Na (/Users/naseemraad/Developer/***/node_modules/tesseract.js-core/index.js:32:26)
    at ka (/Users/naseemraad/Developer/***/node_modules/tesseract.js-core/index.js:507:108)
    at JHa (/Users/naseemraad/Developer/***/node_modules/tesseract.js-core/index.js:402:25808)
    at xd (/Users/naseemraad/Developer/***/node_modules/tesseract.js-core/index.js:382:924)
    at R.TesseractCore.V.Begin (/Users/naseemraad/Developer/***/node_modules/tesseract.js-core/index.js:511:288)
    at DumpLiterallyEverything (/Users/naseemraad/Developer/***/node_modules/tesseract.js/src/common/dump.js:13:8)
    at loadLanguage (/Users/naseemraad/Developer/***/node_modules/tesseract.js/src/common/worker.js:124:22)
    at /Users/naseemraad/Developer/***/node_modules/tesseract.js/src/common/worker.js:92:9
    at /Users/naseemraad/Developer/***/node_modules/tesseract.js/src/node/lang.js:23:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by jeromewu** [comment]
Guess from the sample, I think you are trying to do OCR on a pdf file, which is not supported by tesseract.js (and tesseract as well), that's why you are unable to get any result.

If you really need to support pdf, please consider using image convert library to convert to any supported formats.
