### ISSUE TITLE
error on gif

### ISSUE THREAD

**Issue by armmmo** [naptha/tesseract.js#261]
The strange thing is that it worked on the website.

./imgs/image_2610.gif
progress { status: 'loading tesseract core' }
progress { status: 'loaded tesseract core' }
progress { status: 'initializing tesseract', progress: 0 }
pre-main prep time: 63 ms
progress { status: 'initializing tesseract', progress: 1 }
progress { status: 'loading eng.traineddata', progress: 0 }
progress { status: 'loading eng.traineddata', progress: 1 }
progress { status: 'initializing api', progress: 0 }
progress { status: 'initializing api', progress: 0.3 }
progress { status: 'initializing api', progress: 0.6 }
Error in pixRemoveColormap: pixs must be {1,2,4,8} bpp
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixCreateHeader: depth must be {1, 2, 4, 8, 16, 24, 32}
Error in pixCreateNoInit: pixd not made
Error in pixCreateTemplateNoInit: pixd not made
Error in pixCreateTemplate: pixd not made
Error in pixCopy: pixd not made
progress { status: 'initializing api', progress: 1 }
3
3

C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort(3) at Error
    at Na (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js-core\index.js:32:26)
    at ka (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js-core\index.js:507:108)
    at JHa (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js-core\index.js:402:25808)
    at xd (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js-core\index.js:382:924)
    at R.TesseractCore.V.Begin (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js-core\index.js:511:288)
    at DumpLiterallyEverything (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js\src\common\dump.js:13:8)
    at loadLanguage (C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js\src\common\worker.js:124:22)
    at C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js\src\common\worker.js:92:9
    at C:\Users\Armando-Pc\Desktop\projetos\sandbox-PRO\pupeteer\node_modules\tesseract.js\src\node\lang.js:23:25
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by armmmo** [comment]
tried again, the console gave me infinitely result(coulndt stop printing..)

**Comment by jeromewu** [comment]
Right now git is not supported by tesseract.js, please try other format.
