### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by juniortopanotti** [naptha/tesseract.js#263]
I'm having an error while using the lib, when I make use of the import it ends up with the following error in the console. I am trying to implement the functionality in an application that uses Ionic.
`Uncaught SyntaxError: Unexpected token =
vendor.js:1 ERROR Error: Uncaught (in promise): Error: Loading chunk 0 failed.
Error: Loading chunk 0 failed.
    at HTMLScriptElement.n (http://localhost:8080/build/vendor.js:1:552)
    at HTMLScriptElement.H (http://localhost:8080/build/polyfills.js:3:23950)
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15660)
    at Object.t._inner.t._inner.fork.onInvokeTask (http://localhost:8080/build/vendor.js:1:72627)
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8080/build/polyfills.js:3:10834)
    at e.invokeTask [as invoke] (http://localhost:8080/build/polyfills.js:3:16794)
    at p (http://localhost:8080/build/polyfills.js:2:27648)
    at HTMLScriptElement.v (http://localhost:8080/build/polyfills.js:2:27893)
Error: Loading chunk 0 failed.
    at HTMLScriptElement.n (http://localhost:8080/build/vendor.js:1:552)
    at HTMLScriptElement.H (http://localhost:8080/build/polyfills.js:3:23950)
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15660)
    at Object.t._inner.t._inner.fork.onInvokeTask (http://localhost:8080/build/vendor.js:1:72627)
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8080/build/polyfills.js:3:10834)
    at e.invokeTask [as invoke] (http://localhost:8080/build/polyfills.js:3:16794)
    at p (http://localhost:8080/build/polyfills.js:2:27648)
    at HTMLScriptElement.v (http://localhost:8080/build/polyfills.js:2:27893)
    at c (http://localhost:8080/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8080/build/polyfills.js:3:19174)
    at e._fireError (http://localhost:8080/build/vendor.js:1:437693)
    at e._failed (http://localhost:8080/build/vendor.js:1:437535)
    at http://localhost:8080/build/vendor.js:1:438359
    at t.invoke (http://localhost:8080/build/polyfills.js:3:14976)
    at Object.t._inner.t._inner.fork.onInvoke (http://localhost:8080/build/vendor.js:1:72713)
    at t.invoke (http://localhost:8080/build/polyfills.js:3:14916)
    at r.run (http://localhost:8080/build/polyfills.js:3:10143)
    at http://localhost:8080/build/polyfills.js:3:20242`
I have tried various ways to find a solution, such as installing earlier and recent versions of lib, and so on. I'm not sure where to try to solve it now. My ionic info:
`Ionic:

   ionic (Ionic CLI)  : 4.3.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0
Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 12 other plugins)

System:
   Android SDK Tools : 26.1.1 (D:\ambiente\sdk)
   NodeJS            : v8.11.4 (D:\ambiente\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10`

**Comment by jeromewu** [comment]
@juniortopanotti 

It is pretty hard to find the root cause from your error message, can you provide some code snippet to reproduce the issue?

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information 😄
