### ISSUE TITLE
Can't process any file in Node on Windows/Rasbian

### ISSUE THREAD

**Issue by stonetwig** [naptha/tesseract.js#269]
Hello, I am using the simple example in the guide:

```
const Tesseract = require('tesseract.js')
Tesseract.detect(image)
		.then(function(result){
		    console.log("Result of text:", result)
		})
```

But it always results in this:

```
Error in pixRemoveColormap: pixs must be {1,2,4,8} bpp
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixCreateHeader: depth must be {1, 2, 4, 8, 16, 24, 32}
Error in pixCreateNoInit: pixd not made
Error in pixCreateTemplateNoInit: pixd not made
Error in pixCreateTemplate: pixd not made
Error in pixCopy: pixd not made
Error in pixClipRectangle: pixs not defined
tess->pix_binary() != NULL:Error:Assert failed:in file ../ccmain/osdetect.cpp, line 200
D:\Code\project1\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){
return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })(
)"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (D:\Code\project1\node_modules\tesseract.js-core\index.js:32:26)
    at Object.ka [as abort] (D:\Code\project1\node_modules\tesseract.js-core\index.js:507:108)
    at _abort (D:\Code\project1\node_modules\tesseract.js-core\index.js:373:173)
    at $L (D:\Code\projec1\node_modules\tesseract.js-core\index.js:383:55709)
    at AC (D:\Code\project1\node_modules\tesseract.js-core\index.js:391:60062)
    at Jj (D:\Code\project1\node_modules\tesseract.js-core\index.js:382:34615)
    at bh (D:\Code\project1\node_modules\tesseract.js-core\index.js:382:11059)
    at $.TesseractCore.$.DetectOS (D:\Code\project1\node_modules\tesseract.js-core\index.js:557:88)
    at loadLanguage (D:\Code\project1\node_modules\tesseract.js\src\common\worker.js:144:18)
    at D:\Code\project1\node_modules\tesseract.js\src\common\worker.js:92:9
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

Since the error occurs in osdetect.cpp I am guessing this has something to do with the fact that I am on windows? Can't find anything about windows not being supported but also none seems to have the same issue as me.

I have searched through issues but I have yet to find an answer, would be happy if someone could give some guidance on how I should proceed. I tried to run it on my rasbian rasberry pi, but it also errors out with the same kind of error.

Version: `"tesseract.js": "^1.0.14"`

Thank you!

**Comment by stonetwig** [comment]
Seems like I made a very basic error, trying to send in a normal javascript object instead of a file buffer.
