### ISSUE TITLE
Create PDF Path

### ISSUE THREAD

**Issue by MaxvandeLaar** [naptha/tesseract.js#289]
I am using Tesseract.JS with NodeJS on a server and I am generating PDF files based on uploaded images. I know this is possible by setting `'create_pdf' : '1'`. I can set the PDF name by setting `'pdf_name' : 'my-ocr-pdf'`. This al works perfectly. However, the PDF file always ends up in the root of my project. 

I would like to set a custom path to a different subfolder. Is this possible? If so, how, if not, I would like to submit a feature request :)

I tried settings the path to the folder in the pdf_name such as `'pdf_name': '/User/Me/MyProject/Storage/my-ocr-pdf'`, however this results in an error: 

```
{ Error
    at new ErrnoError (/Users/Me/MyProject/node_modules/tesseract.js-core/tesseract-core.js:8:84365)
    at Object.open (/Users/Me/MyProject/node_modules/tesseract.js-core/tesseract-core.js:8:76008)
    at Object.readFile (/Users/Me/MyProject/node_modules/tesseract.js-core/tesseract-core.js:8:80760)
    at handleOutput (/Users/Me/MyProject/node_modules/tesseract.js/src/common/workerUtils.js:110:32)
    at loadLanguage.catch.then (/Users/Me/MyProject/node_modules/tesseract.js/src/common/workerUtils.js:221:25)
  node: undefined,
  setErrno: [Function],
  errno: 2,
  code: 'ENOENT',
  message: 'No such file or directory' }

/Users/Me/MyProject/node_modules/tesseract.js-core/tesseract-core.js:8
var Module=typeof TesseractCoreWASM!=="undefined"?TesseractCoreWASM:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}else{return scriptDirectory+path}}if(EN
abort({"errno":2,"code":"ENOENT","message":"No such file or directory"}). Build with -s ASSERTIONS=1 for more info.
```

I am running Node v10.15.3 on MacOS Majove 10.14.4

**Comment by MaxvandeLaar** [comment]
So I sort of figured it out by using `'pdf_bin': true` to create my own pdf file.
