### ISSUE TITLE
TypeError: Cannot read property 'SetVariable' of null

### ISSUE THREAD

**Issue by aeisenberg** [naptha/tesseract.js#354]
**Describe the bug**
I am getting a type error when I call the `Worker.setParameter` method. I am using v2.0.0-beta.1 on node v12.13.0.

**To Reproduce**
Steps to reproduce the behavior, run this snippet:

```
const Tesseract = require('tesseract.js');

(async () => {
  const worker = Tesseract.createWorker({
  });
  await worker.setParameters({
    tessedit_char_whitelist: '0123456789',
  });
})();
```

Here is the full stack trace: 

```
Error: TypeError: Cannot read property 'SetVariable' of null
    at ChildProcess.<anonymous> (/Users/andrew.eisenberg/Eclipse/git-repos/tesseract-playing/node_modules/tesseract.js/src/createWorker.js:135:13)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Expected behavior**

**Desktop (please complete the following information):**
 - MacOS Catalina
 - node v12.13.0.
 - Tesseract.js Version v2.0.0-beta.1

**Comment by aeisenberg** [comment]
My mistake. I need to call the following before calling `setParameter`:

```
  await worker.load();
  await worker.loadLanguage('mrz');
  await worker.initialize('mrz');
```
