### ISSUE TITLE
TypeError: Worker is not a constructor

### ISSUE THREAD

**Issue by 350478992** [naptha/tesseract.js#406]
Uncaught (in promise) thirdScriptError
Worker is not a constructor
TypeError: Worker is not a constructor
    at module.exports (weapp:///common/vendor.js:9941:16)
    at module.exports (weapp:///common/vendor.js:9150:18)
    at VueComponent._callee$ (weapp:///pages/index/index.js:226:63)
    at tryCatch (weapp:///common/vendor.js:8138:42)
    at Generator.invoke [as _invoke] (weapp:///common/vendor.js:8349:24)
    at Generator.prototype.<computed> [as next] (weapp:///common/vendor.js:8186:23)
    at asyncGeneratorStep (weapp:///pages/index/index.js:177:28)
    at _next (weapp:///pages/index/index.js:190:13)
    at eval (weapp:///pages/index/index.js:193:12)
    at new Promise (<anonymous>)

I used tesseract.js v2. ("tesseract.js": "^2.0.0-beta.2")
Please suggest a solution

**Comment by jeromewu** [comment]
Can you provide the a sample code to reproduce this issue? Thanks.

**Comment by jeromewu** [comment]
Close due to inactivity.
