### ISSUE TITLE
Tesseractjs recognize Error: abort(21). Build with -s ASSERTIONS=1 for more info

### ISSUE THREAD

**Issue by BradleyBrown19** [naptha/tesseract.js#429]
I am using tesseract.js in my electron project (tesseractjs 2.0.2, electron 8.1.0). When executing the following code:
```
let worker = await createWorker({
        langPath: "ocr_data",
        logger: m => console.log(m)
    });
    await worker.load();
    await worker.loadLanguage("eng");
    await worker.initialize('eng');
    try {
        let {data: {text}} = await worker.recognize(path.join(__dirname, 'test', 'test.png'))
        await worker.terminate();
        return text
    } catch(e) {
        console.log(e)
    }
```

I get the following error:

```
 Error: abort(21). Build with -s ASSERTIONS=1 for more info.
    at createWorker.js:141
```

This error occurs at worker.recognize...
I am unsure of what it means in the error message. Please let me know if you have any ideas on how to fix or get more debug info! Thanks.

**Comment by jeromewu** [comment]
I think the root cause might be the path of your `langPath`, please take a look at this repository and see if it works in your environment.

https://github.com/jeromewu/tesseract.js-electron

**Comment by dimatter** [comment]
```❯ node main.js
{ status: 'loading tesseract core', progress: 0 }
{ status: 'loaded tesseract core', progress: 1 }
{ workerId: 'Worker-0-e34c2',
  status: 'initializing tesseract',
  progress: 0 }
{ workerId: 'Worker-0-e34c2',
  status: 'initialized tesseract',
  progress: 1 }
{ workerId: 'Worker-0-e34c2',
  status: 'loading language traineddata',
  progress: 0 }
{ workerId: 'Worker-0-e34c2',
  status: 'loaded language traineddata',
  progress: 1 }
{ workerId: 'Worker-0-e34c2',
  status: 'initializing api',
  progress: 0 }
{ workerId: 'Worker-0-e34c2',
  status: 'initialized api',
  progress: 1 }
Error in pixReadMem: size < 12
Error in pixGetSpp: pix not defined
Error in pixGetDimensions: pix not defined
Error in pixGetColormap: pix not defined
Error in pixCopy: pixs not defined
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixGetYRes: pix not defined
Error in pixClone: pixs not defined
Please call SetImage before attempting recognition.
21
21
/Users/igvar/sandbox/tesseract.js-electron/node_modules/tesseract.js/src/createWorker.js:139
        throw Error(data);
        ^

Error: abort(21). Build with -s ASSERTIONS=1 for more info.
    at ChildProcess.onMessage (/Users/igvar/sandbox/tesseract.js-electron/node_modules/tesseract.js/src/createWorker.js:139:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)```

**Comment by jeromewu** [comment]
Close due to inactivity.
