### ISSUE TITLE
Why my code didn't work...

### ISSUE THREAD

**Issue by winnerweb** [naptha/tesseract.js#48]
My code:
```javascript
const path = require('path');
const Tesseract = require('tesseract.js');
const myImage = path.resolve(__dirname, 'out.png');
Tesseract.recognize(myImage)
    .progress(message => console.log(message))
    .catch(err => console.error(err))
    .then(result => console.log(result))
    .finally(resultOrError => console.log(resultOrError))
```

Issues: 
```
/Users/xuyan/Documents/my/node/login/node_modules/tesseract.js/src/index.js:15
class TesseractWorker {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/xuyan/Documents/my/node/login/testPng.js:3:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by bijection** [comment]
what version of node are you using?

**Comment by winnerweb** [comment]
node -v
v5.1.0

**Comment by rowasc** [comment]
Hi @winnerweb 
From the README.md file: 
`Note: Tesseract.js currently requires node v6.8.0 or greater.`
so that's probably it.

**Comment by bijection** [comment]
Thanks @rowasc! 
You're right, @winnerweb you'll need to update node to use Tesseract.js.

**Comment by winnerweb** [comment]
@bijection @rowasc Thanks, I will try it...

**Comment by tetreault** [comment]
This is what I get for not fully reading the README 🤦‍♂️

**Comment by fjlogrono** [comment]
I'm getting the same error, but when I put a cordova project.
In angular 5 in desktop it works correctly (With node 9)

**Comment by jeromewu** [comment]
When you are getting the same error, which node version are you using?

**Comment by fjlogrono** [comment]
Excuse me, I'm stupid.
I am using local, node version 9.0

But of course, if I add to cordoba the generated in angular CLI, there is no node.

So what I've done is use the CDN.
Thanks and sorry for the inconvenience.
