### ISSUE TITLE
problem with Arabic recognition

### ISSUE THREAD

**Issue by Dreamersoul** [naptha/tesseract.js#51]
So I'm using this code provided by @zeke, English text gets recognized fine but this error appears whenever I am using the Arabic recognizer.
## Code
```javascript
const path = require('path')
const Tesseract = require('tesseract.js')

const file = require('fs').readFileSync(path.join(__dirname, 'arabic-3.png'))

Tesseract.recognize(file, {lang: 'ara'})
  .progress(message => console.log(message))
  .catch(err => console.error(err))
  .then(result => console.log(result))
```
## Error
```javascript
/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort(5) at Error
    at Error (native)
    at Na (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:32:26)
    at ka (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:507:108)
    at Array.LHa (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:402:25912)
    at Qpa (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:388:44877)
    at kpa (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:388:23029)
    at jpa (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:388:22303)
    at lT (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:387:80568)
    at mT (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:387:80700)
    at Array.BS (/Users/macbook/Development/projects/nodejs/ocr-test/node_modules/tesseract.js/node_modules/tesseract.js-core/index.js:387:69011)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by bijection** [comment]
We're aware of this problem. See #30

**Comment by santhoshGPD** [comment]
English text gets recognized successfully but i trying to Arabic text its getting .

Uncaught abort(5) at Error
    at Na (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:36:26)
    at ka (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:511:108)
    at LHa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:406:25912)
    at Qpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:44877)
    at kpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:23029)
    at jpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:22303)
    at lT (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:80568)
    at mT (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:80700)
    at BS (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:69011)
    at bP (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:387:110121)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

  help me.
