### ISSUE TITLE
Error - RangeError: Invalid string length 

### ISSUE THREAD

**Issue by fishcharlie** [naptha/tesseract.js#533]
**Describe the bug**

Getting an error (`RangeError: Invalid string length`) when trying to run `worker.recognize`.

**To Reproduce**
1. Run the code below
2. Notice that error occurs

```js
const tesseract = require("tesseract.js");
const fs = require("fs").promises;

const worker = tesseract.createWorker({
  logger: m => console.log(m)
});

(async () => {
  await worker.load();
  await worker.loadLanguage('eng');
  await worker.initialize('eng');
  const file = await fs.readFile("/Users/charliefish/Downloads/StreetImage2.png");
  console.log("HERE");
  const { data: { text } } = await worker.recognize(file);
  console.log(text);
  await worker.terminate();
})();
```

**Expected behavior**

No errors to occur.

**Desktop (please complete the following information):**

 - OS: macOS 
 - Browser: Node.js
 - Version: v15.14.0

**Additional context**

The image is 3840px x 2160px png image which is 39.1 MB large. I attempted this on a jpg image that was 579px x 195px and 23 K large and it worked fine (no errors).

I'd be happy to provide the image I'm trying to use, however it does contain information that although not private, data that I would not like to be public either. If this would be helpful in the debugging process, please let me know of a secure/private way to transmit this image to you.

Output Log & Stack Trace:

```
charliefish@Charlies-MacBook-Pro Interface % node ocrtest.js
{ status: 'loading tesseract core', progress: 0 }
{ status: 'loaded tesseract core', progress: 1 }
{
  workerId: 'Worker-0-7cc2f',
  status: 'initializing tesseract',
  progress: 0
}
{
  workerId: 'Worker-0-7cc2f',
  status: 'initialized tesseract',
  progress: 1
}
{
  workerId: 'Worker-0-7cc2f',
  status: 'loading language traineddata',
  progress: 0
}
{
  workerId: 'Worker-0-7cc2f',
  status: 'loading language traineddata (from cache)',
  progress: 0.5
}
{
  workerId: 'Worker-0-7cc2f',
  status: 'loaded language traineddata',
  progress: 1
}
{ workerId: 'Worker-0-7cc2f', status: 'initializing api', progress: 0 }
{ workerId: 'Worker-0-7cc2f', status: 'initialized api', progress: 1 }
HERE
node:internal/child_process/serialization:120
    const string = JSONStringify(message) + '\n';
                   ^

RangeError: Invalid string length
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:120:20)
    at ChildProcess.target._send (node:internal/child_process:822:17)
    at ChildProcess.target.send (node:internal/child_process:722:19)
    at module.exports (/Users/charliefish/Developer/fishcharlie/Project/Interface/node_modules/tesseract.js/src/worker/node/send.js:9:10)
    at /Users/charliefish/Developer/fishcharlie/Project/Interface/node_modules/tesseract.js/src/createWorker.js:47:7
    at new Promise (<anonymous>)
    at startJob (/Users/charliefish/Developer/fishcharlie/Project/Interface/node_modules/tesseract.js/src/createWorker.js:43:5)
    at Object.recognize (/Users/charliefish/Developer/fishcharlie/Project/Interface/node_modules/tesseract.js/src/createWorker.js:119:5)
    at async /Users/charliefish/Developer/fishcharlie/Project/Interface/ocrtest.js:14:30
```

**Comment by Balearica** [comment]
The bugs/performance issues with large images should have been resolved in the latest version of Tesseract.js (v3).  If this issue is still active, please try again using the latest version.

**Comment by Balearica** [comment]
Closing as resolved.  Feel free to reopen if you can reproduce this error in the latest version.
