### ISSUE TITLE
Error found manipulating PNG for #53 - Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by rowasc** [naptha/tesseract.js#54]
`Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 100663296, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.`
`Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 100663296, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.`

`/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;`
              
`abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 100663296, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.") at Error
    at Error (native)
    at Na (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:32:26)
    at ka (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:507:108)
    at Function.pb (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:12:26)
    at vd (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:331:190)
    at UFa (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:396:56010)
    at WEa (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:396:39452)
    at Gra (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:388:78184)
    at Mpa (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:388:42487)
    at Rpa (/Test-Projects/tesseract.js/node_modules/tesseract.js-core/index.js:388:45819)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.`

**Comment by rowasc** [comment]
![jpgpng-bigfile](https://cloud.githubusercontent.com/assets/2434401/19461328/2cd0f2c4-94ba-11e6-8725-ec445bed2530.png)
uploading the file I was using at the time.

**Comment by rowasc** [comment]
Apparently, I messed something up in the desaturate function while doing some weird test, it's back to normal after a checkout . 👎 I will be back if I find that it happens when users don't mess things up :|

**Comment by arisAlexis** [comment]
I also get this message

**Comment by ashokkumarjuly** [comment]
I too facing this issue.
Image size : 2.6 mb
Resolution: 5120x2840

**Comment by ryanfb** [comment]
I think this is the same issue as #100.
