### ISSUE TITLE
Is there a version of tesseract.js that does not reference the "window" object?

### ISSUE THREAD

**Issue by skanga** [naptha/tesseract.js#559]
I am trying to run Tesseract.js on GraalVM using its graal.js functionality but could not get it to work.

Here is what I tried.

```
public static final String TESSERACT = "src/tesseract.js";

private static void tesseract(String imageFile) throws IOException
{
    System.out.println("=== Calling Tesseract === ");
    try(Context context = Context.create())
    {
        context.eval(Source.newBuilder("js", new File(TESSERACT)).build());
        Value Tesseract = context.getBindings("js").getMember("Tesseract");
        Value recognize = Tesseract.getMember("recognize");
        long start = System.currentTimeMillis();
        String result = recognize.execute(imageFile).asString();
        long took = System.currentTimeMillis() - start;
        System.out.println("Tesseract call took: " + took + "ms with result: " + result);
    } // context.close() is automatic
}
```
And it compiles but at runtime throws this exception:

```
=== Calling Tesseract === 
Exception in thread "main" ReferenceError: window is not defined
    at <js> spawnWorker(src\tesseract.js:286:8848-8853)
    at <js> _delay(src\tesseract.js:504:16140-16184)
    at <js> recognize(src\tesseract.js:472-481:15321-15620)
    at org.graalvm.polyglot.Value.execute(Value.java:457)
    at com.mycompany.app.JsApp.tesseract(JsApp.java:98)
    at com.mycompany.app.JsApp.main(JsApp.java:70)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

Anyone know to to fix this?

**Comment by Balearica** [comment]
@skanga The build was updated in the last release (now uses Webpack 5), so it's at least plausible that this behavior has changed.  If this issue is still active can you confirm you still get this exception using the current release?

**Comment by Balearica** [comment]
Closing as stale.  Feel free to reopen if you can reproduce using the latest version.
