### ISSUE TITLE
addEventListener is not a function

### ISSUE THREAD

**Issue by StefanoVe** [naptha/tesseract.js#626]
I'm trying to implement tesseract.js in an express route  of a NX monorepo and i cannot get rid of this error:
```js
TypeError: t.addEventListener is not a function
    at Object.<anonymous> (/Users/vecho/Dev-Stuff/Projects/Golden/golden/node_modules/tesseract.js/dist/worker.min.js:8:36139)
    at Object.<anonymous> (/Users/vecho/Dev-Stuff/Projects/Golden/golden/node_modules/tesseract.js/dist/worker.min.js:8:36665)
    at r (/Users/vecho/Dev-Stuff/Projects/Golden/golden/node_modules/tesseract.js/dist/worker.min.js:1:110)
    at /Users/vecho/Dev-Stuff/Projects/Golden/golden/node_modules/tesseract.js/dist/worker.min.js:1:902
    at Object.<anonymous> (/Users/vecho/Dev-Stuff/Projects/Golden/golden/node_modules/tesseract.js/dist/worker.min.js:1:911)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

It seems to be generating from within the worker but i'm importing it straight from the library so i really don't know what to do to fix it.
I've tried using another worker i've found in the examples page and that too results the same error

```js
TypeError: global.addEventListener is not a function
    at Object.<anonymous> (/Users/vecho/Dev-Stuff/Projects/Golden/golden/assets/worker.js:9862:18)
    at Object.39.../common/worker.js (/Users/vecho/Dev-Stuff/Projects/Golden/golden/assets/worker.js:9881:11)
    at s (/Users/vecho/Dev-Stuff/Projects/Golden/golden/assets/worker.js:12:15)
    at e (/Users/vecho/Dev-Stuff/Projects/Golden/golden/assets/worker.js:29:38)
    at Object.<anonymous> (/Users/vecho/Dev-Stuff/Projects/Golden/golden/assets/worker.js:31:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

```

this is how i've been trying to implement tesseract

```ts
import * as Tesseract from 'tesseract.js';

router.post(
  '/',
  body('imageData').isString().withMessage(`Invalid Image`),
  validateRequest,
  requireAuth,
  async (req: express.Request, res: express.Response) => {
    const imageBuffer = Buffer.from(req.body.imageData);

    const result = await Tesseract.recognize(imageBuffer, 'eng', {
      logger: (m) => console.log(m),
      workerPath: 'node_modules/tesseract.js/dist/worker.min.js',
      langPath: 'assets/eng.traineddata',
    }).catch(genericErrorHandler);

    Logger.info(result.data);

    res.send({ data: 'ok' });
  }
);
```

**Comment by StefanoVe** [comment]
Solved it by creating a separate node project just to handle tesseract.js

**Comment by StefanoVe** [comment]
Solved it by creating a separate node project just to handle tesseract.js as it seems nx was the issue
