### ISSUE TITLE
SyntaxError: Unexpected token '?' in dump.js

### ISSUE THREAD

**Issue by tefracky** [naptha/tesseract.js#694]
**Describe the bug**
SyntaxError: Unexpected token '?' in dump.js

**To Reproduce**
1. Download the Git
2. Go to 'examples/node/'
3. Run 'node detect.js'

**Expected behavior**
The example should run without error.

**Desktop (please complete the following information):**
 - OS: Raspbian Bullseye 64-Bit
 - Version: Tesseract 4.0.0

**Additional context**
```
***@Raspi-4:~/nextcloud/Befehle/NodeJS/Tesseract/examples/node $ node detect
Recognizing /home/***/nextcloud/Befehle/NodeJS/Tesseract/tests/assets/images/cosmic.png

events.js:291
      throw er; // Unhandled 'error' event
      ^
/home/***/nextcloud/Befehle/NodeJS/Tesseract/src/worker-script/utils/dump.js:211
    pdf: output.pdf ? getPDFInternal(options.pdfTitle ?? 'Tesseract OCR Result', options.pdfTextOnly ?? false) : null,
                                                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/***/nextcloud/Befehle/NodeJS/Tesseract/src/worker-script/index.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:251:10)
    at Worker.[kOnMessage] (internal/worker.js:262:37)
    at MessagePort.<anonymous> (internal/worker.js:171:57)
    at MessagePort.emit (events.js:314:20)
    at MessagePort.onmessage (internal/worker/io.js:80:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```

**Comment by tefracky** [comment]
Forget it, I just had to update npm to 9.1.3 (coming from 8...).

**Comment by zhaiyjgithub** [comment]
node 14 or higher.
