### ISSUE TITLE
I'm getting text from image with the given example was working fine on my local environment but getting this after deployment on vercel.

### ISSUE THREAD

**Issue by Neeraj-mvrk** [naptha/tesseract.js#706]
Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/tesseract.js-core/tesseract-core-simd.wasm')
2023-01-04T16:40:42.040Z	646dc58c-78e6-49aa-b925-7c488023f4e7	ERROR	Uncaught Exception 	{"errorType":"RuntimeError","errorMessage":"Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/tesseract.js-core/tesseract-core-simd.wasm'). Build with -sASSERTIONS for more info.","stack":["RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/tesseract.js-core/tesseract-core-simd.wasm'). Build with -sASSERTIONS for more info.","    at n (/var/task/node_modules/tesseract.js-core/tesseract-core-simd.js:18:375)","    at Ua (/var/task/node_modules/tesseract.js-core/tesseract-core-simd.js:19:317)","    at /var/task/node_modules/tesseract.js-core/tesseract-core-simd.js:20:394"]}
Unknown application error occurred
Runtime.Unknown

Node version -18.12.1

**Comment by Balearica** [comment]
This error looks completely literal--your deployed version did not have the script specified in the expected location.  You need to investigate why that is, and if you're not sure and would like assistance then link to your project repository so others can look.

**Comment by Neeraj-mvrk** [comment]
> This error looks completely literal--your deployed version did not have the script specified in the expected location. You need to investigate why that is, and if you're not sure and would like assistance then link to your project repository so others can look.

Thanks for the reply, as you said I checked that, and the first file load when image processing started was ( tesseract.js-core/tesseract-core-simd) but the file which was not located by vercel is (tesseract.js-core/tesseract-core-simd.wasm) which is a web assembly file. This file load before the latter one. If the whole module is not present then the first error should be (uncaughtException: Error: Error: Cannot find module 'tesseract.js-core/tesseract-core-simd').

**Comment by Balearica** [comment]
I'm confused regarding what you are suggesting.  Are you claiming that `/var/task/node_modules/tesseract.js-core/tesseract-core-simd.wasm` does exit? 

To clarify, there is no file named `tesseract-core-simd`.  Any reference to `tesseract-core-simd` in this codebase is simply omitting the file extension--the relevant file is `tesseract-core-simd.wasm`.

**Comment by Balearica** [comment]
Closing as stale.

**Comment by ariburaco** [comment]
I am having the same problem. Is there any solution for that? 

I am using a turborepo, based on this template: https://github.com/clerkinc/t3-turbo-and-clerk
