### ISSUE TITLE
webpack support

### ISSUE THREAD

**Issue by rudzikdawid** [naptha/tesseract.js#77]
using webpack, trying to load module like:
```
const tesseract = require('tesseract.js');
```

i have error:
```
ERROR in ./~/tesseract.js/package.json
Module parse failed: /home/mike_oldfield/tesseract/node_modules/tesseract.js/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/mike_oldfield/tesseract/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/tesseract.js/src/index.js 5:16-42
```

becouse tesseract.js/package.json

```
"main": "src/index.js"
```

**To fix this we need to change "main" in package.json**
```
"main": "dist/tesseract.js"
```

with this litle change, module is loading properly using webpack

**Comment by yowakita** [comment]
Thanks @rudzikdawid, that error was driving me crazy and I couldn't figure out the cause of it (I'm pretty raw with Webpack still.) 
It does compile but now gets a new warning:

```
WARNING in ./~/tesseract.js/dist/tesseract.js
Critical dependencies:
26:88-96 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/tesseract.js/dist/tesseract.js 26:88-96
```

**Comment by antimatter15** [comment]
Try using

```
const Tesseract = require('tesseract.js/dist/tesseract.js');
```

The main problem is that Webpack ignores the `package.json` field `"browser"` and loads `src/index.js` anyway which is intended for NodeJS environments. The pre-built `dist/tesseract.js` warning is expected and totally harmless. 

If for some reason you really want to be able to load `tesseract.js/src/index.js`, make sure you're running webpack with json-loader, and babel.

**Comment by yowakita** [comment]
Thanks @antimatter15 . When I attempted to `recognize` an image, i got this error: 
```DOMException: Failed to execute 'postMessage' on 'Worker': An object could not be cloned.
    at eval (webpack:///../~/tesseract.js/dist/tesseract.js?:385:41)
    at loadImage (webpack:///../~/tesseract.js/dist/tesseract.js?:444:32)
    at Object.sendPacket (webpack:///../~/tesseract.js/dist/tesseract.js?:383:21)
    at TesseractJob._send (webpack:///../~/tesseract.js/dist/tesseract.js?:588:33)
    at eval (webpack:///../~/tesseract.js/dist/tesseract.js?:693:33)
    at Array.eval (webpack:///../~/tesseract.js/dist/tesseract.js?:723:29)
    at TesseractWorker._dequeue (webpack:///../~/tesseract.js/dist/tesseract.js?:733:43)
    at TesseractWorker._delay (webpack:///../~/tesseract.js/dist/tesseract.js?:725:53)
    at TesseractWorker.recognize (webpack:///../~/tesseract.js/dist/tesseract.js?:685:37)
    at eval (webpack:///./utilities/tesseract.js?:11:15)```

I saw that this commit modified the `src/index.js` https://github.com/naptha/tesseract.js/commit/15bb5c41459a7478bab70546bdcd80c532454391

Does the `dist/tesseract` file need to be updated too?

**Comment by yowakita** [comment]
@antimatter15 can you respond to this?

**Comment by antimatter15** [comment]
What image are you trying to recognize?

**Comment by yowakita** [comment]
I've tried on a few different files, for example, this picture of a stop sign: 
![stop-sign-clipart-z7tam5xia](https://cloud.githubusercontent.com/assets/11986887/20373771/f544d02e-ac28-11e6-980d-618e95740aba.png)
