### ISSUE TITLE
Error: FetchError: request to https://cdn.jsdelivr.net/npm/@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz failed, reason: getaddrinfo ENOTFOUND cdn.jsdelivr.net

### ISSUE THREAD

**Issue by JemiArtistaa** [naptha/tesseract.js#976]
**Tesseract.js version (5.1.1)**

**Describe the bug**
I am attempting to take screenshot of a text captcha and trying to extract text from that screenshot using Tesseract in my playwright test.

**Code**

```
test('asdas', async({page})=>{
    await page.goto('....')
    await page.getByText('Proceed').click()

    let imgName = Date.now()
    await page.locator('div[id="customCaptcha"]>div:nth-child(1) input[type="text"]')
              .screenshot({ path: `${imgName}.png`});
    await convertImageToText(`${imgName}.png`)
})

async function convertImageToText(imageName) {

    const worker = await Tesseract.createWorker('eng');

    let imgText = await worker.recognize(`./${imageName}`)
    console.log(imgText.data.text)
}
```

**Expected behavior**
text should be extracted from the screenshot

**Device Version:**

 - OS + Version: [Windows 10]
 - Browser [chrome] or Node version [Node v20.11.1]

**Additional context**
I am running behind proxy and proxy(both https and http) is set properly since without proxy I can not install npm packages.

**Comment by JemiArtistaa** [comment]
I tried the local solution and now getting following error :

```
    TypeError: r.g.addEventListener is not a function
        at C:\AutomationPractice\Playwright\two\node_modules\tesseract.js\dist\worker.min.js:2:123086
        at C:\AutomationPractice\Playwright\two\node_modules\tesseract.js\dist\worker.min.js:2:123611
        at Object.<anonymous> (C:\AutomationPractice\Playwright\two\node_modules\tesseract.js\dist\worker.min.js:2:123615)
```

**Comment by JemiArtistaa** [comment]
Issue solved.
 
1. Downloaded the language data pack. 
2. Place it in project directory
3. create worker with langpath.

Code as follows:
```
import Tesseract from 'tesseract.js'; 

await page.goto('....')
await page.getByText('Proceed').click()

let imgName = Date.now()
await page.locator('div[id="customCaptcha"]>div:nth-child(1) input[type="text"]')
                  .screenshot({ path: `${imgName}.png`});
await convertImageToText(`${imgName}.png`)

async function convertImageToText(imageName) {
  
    const worker = await Tesseract.createWorker('eng', 1, {
        langPath: './TesseractLanguageBundle/',
      });

    let imgText = await worker.recognize(`./${imageName}`)
    console.log(imgText.data.text)
}
```
